spring:
  datasource:
    url: jdbc:mysql://47.102.217.84:3306/smt_data?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: 'Bxyssz724'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
